Repository Firoso/Valheim-Dusk-Niflheim, pull requests merged in 2021-04, with the labels that each got.

#1 Initing hotfixes; fixed gamble prices to better match the max potenti…
  mod_root/BepInEx/plugins/EpicLoot/adventuredata.json
Labels: bug, fix

#2 Adding modbins.json to describe where modpack binaries can be resolved
  mod_root/modbins.json
Labels: enhancement

#4 Vendor Fix
  mod_root/BepInEx/plugins/BetterTrader/item_defaults.cfg
Labels: bug, fix

#30 First pass at mountains and Moder
  mod_root/BepInEx/plugins/CreatureControl/CreatureConfig.yaml
  mod_root/BepInEx/plugins/CreatureControl/CreatureConfig.yml
Labels: UX, enhancement, good first issue

#32 Dev/niflheim 1.2.0 tweaks
  mod_root/BepInEx/plugins/BetterTrader/item_defaults.cfg
  mod_root/BepInEx/plugins/CreatureControl/CreatureConfig.yml
  mod_root/BepInEx/plugins/EpicLoot/loottables.json
Labels: UX, enhancement
